workflows:
  dailykind-debug:
    name: DailyKind Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - my-debug-keystore
      vars:
        FIREBASE_APP_ID: 1:884358901774:android:6c7a60fb2942902904cc5f
      flutter: stable
      java: 11
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Build APK
        script: flutter build apk --debug
      
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - vinka.aeris@gmail.com
        notify:
          success: true
          failure: true

  dailykind-release:
    name: DailyKind Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - my-release-keystore
      vars:
        FIREBASE_APP_ID: 1:884358901774:android:6c7a60fb2942902904cc5f
      flutter: stable
      java: 11
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Build Release
        script: |
          flutter build apk --release
          flutter build appbundle --release
      
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    
    publishing:
      email:
        recipients:
          - vinka.aeris@gmail.com
        notify:
          success: true
          failure: true