// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQbCDHdPsbspSD4Af4PAtCRUMsSQFTOAU',
    appId: '1:884358901774:web:c48483c651468a1804cc5f',
    messagingSenderId: '884358901774',
    projectId: 'dailykind-50ac3',
    authDomain: 'dailykind-50ac3.firebaseapp.com',
    storageBucket: 'dailykind-50ac3.firebasestorage.app',
    measurementId: 'G-1SVF5GK8Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzeazjI2EC_KWVy0kIoEFzI-o1ArB4Utk',
    appId: '1:884358901774:android:6c7a60fb2942902904cc5f',
    messagingSenderId: '884358901774',
    projectId: 'dailykind-50ac3',
    storageBucket: 'dailykind-50ac3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3DtYjSKnUfZcPUfvXz1XtRyHydmfJa9s',
    appId: '1:884358901774:ios:74c1fb80150ac3f604cc5f',
    messagingSenderId: '884358901774',
    projectId: 'dailykind-50ac3',
    storageBucket: 'dailykind-50ac3.firebasestorage.app',
    iosBundleId: 'com.example.dailykindFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3DtYjSKnUfZcPUfvXz1XtRyHydmfJa9s',
    appId: '1:884358901774:ios:74c1fb80150ac3f604cc5f',
    messagingSenderId: '884358901774',
    projectId: 'dailykind-50ac3',
    storageBucket: 'dailykind-50ac3.firebasestorage.app',
    iosBundleId: 'com.example.dailykindFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQbCDHdPsbspSD4Af4PAtCRUMsSQFTOAU',
    appId: '1:884358901774:web:909561ac76cc705c04cc5f',
    messagingSenderId: '884358901774',
    projectId: 'dailykind-50ac3',
    authDomain: 'dailykind-50ac3.firebaseapp.com',
    storageBucket: 'dailykind-50ac3.firebasestorage.app',
    measurementId: 'G-2L8NJFZD87',
  );
}
